#!/bin/sh

mute="$(pulsemixer --get-mute)"
vol="$(pulsemixer --get-volume | awk '{print $1}')"

if [ $mute = 1 ]; then
    printf " Muted"
else
    case ${vol%?} in
        [6-9]|10) i='' ;;
           [3-5]) i='' ;;
               *) i=''
    esac
    printf "%s%%\n" "$i $vol"
fi
